# Generated by Django 4.2.29 on 2026-03-26 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_add_store_id'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_user_id_ea8c9f_idx',
            old_name='audit_audit_user_id_7b2b0d_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_object__1f9df3_idx',
            old_name='audit_audit_object__a8e0a0_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_timesta_901180_idx',
            old_name='audit_audit_timesta_9c1e2a_idx',
        ),
    ]
