# Generated by Django 4.2.29 on 2026-03-13 02:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_consolidate_pricing_inventory_remove_legacy'),
        ('sync', '0002_syncschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSyncRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='running', max_length=20)),
                ('listings_processed', models.IntegerField(default=0)),
                ('listings_updated', models.IntegerField(default=0)),
                ('error_summary', models.TextField(blank=True, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_runs', to='stores.store')),
            ],
            options={
                'db_table': 'sync_storesyncrun',
                'ordering': ['-started_at'],
            },
        ),
        migrations.DeleteModel(
            name='SyncJob',
        ),
        migrations.AddField(
            model_name='synclog',
            name='sync_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='sync.storesyncrun'),
        ),
    ]
