# Generated by Django 4.2.29 on 2026-03-17 17:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_catalogupload_productmapping_is_active_and_more'),
        ('stores', '0008_alter_storeinventoryrangemultiplier_fixed_value_and_more'),
        ('sync', '0005_drop_orders_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('rows_processed', models.PositiveIntegerField(default=0)),
                ('rows_succeeded', models.PositiveIntegerField(default=0)),
                ('error_summary', models.TextField(blank=True, null=True)),
                ('catalog_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrape_runs', to='catalog.catalogupload')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrape_runs', to='stores.store')),
            ],
            options={
                'db_table': 'sync_scraperun',
                'ordering': ['-started_at'],
            },
        ),
    ]
