# Generated by Django 4.2.29 on 2026-07-13 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0022_store_lasoo_environment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_order_key', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('invoice_number', models.CharField(blank=True, default='', max_length=255)),
                ('customer_info_json', models.JSONField(blank=True, null=True)),
                ('line_items_json', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('sent', 'Sent'), ('shipping_submitted', 'Shipping Submitted'), ('shipping_complete', 'Shipping Complete')], db_index=True, default='new', max_length=30)),
                ('shipping_status', models.CharField(default='pending', max_length=30)),
                ('total_amount_cents', models.IntegerField(blank=True, null=True)),
                ('raw_response_json', models.JSONField(blank=True, null=True)),
                ('environment', models.CharField(choices=[('staging', 'Staging'), ('production', 'Production')], default='staging', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_orders', to='stores.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'listings_marketplaceorder',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderShipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_number', models.CharField(blank=True, default='', max_length=255)),
                ('carrier', models.CharField(blank=True, default='', max_length=255)),
                ('tracking_url', models.URLField(blank=True, default='', max_length=1000)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('marketplace_request_json', models.JSONField(blank=True, null=True)),
                ('marketplace_response_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='listings.marketplaceorder')),
            ],
            options={
                'db_table': 'listings_ordershipment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_product_key', models.CharField(max_length=255)),
                ('external_variant_key', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('brand', models.CharField(blank=True, default='', max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=500)),
                ('sku', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('barcode', models.CharField(blank=True, default='', max_length=255)),
                ('image_urls', models.TextField(blank=True, default='')),
                ('inventory', models.IntegerField(default=0)),
                ('infinite_quantity', models.BooleanField(default=False)),
                ('original_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('original_price_cents', models.IntegerField(default=0)),
                ('sale_price_cents', models.IntegerField(default=0)),
                ('external_data_object_json', models.TextField(blank=True, default='')),
                ('environment', models.CharField(choices=[('staging', 'Staging'), ('production', 'Production')], default='staging', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('validation_failed', 'Validation Failed'), ('ready', 'Ready'), ('uploaded_staging', 'Uploaded (Staging)'), ('uploaded_production', 'Uploaded (Production)'), ('failed', 'Upload Failed')], db_index=True, default='draft', max_length=30)),
                ('validation_errors_json', models.JSONField(blank=True, null=True)),
                ('marketplace_request_json', models.JSONField(blank=True, null=True)),
                ('marketplace_response_json', models.JSONField(blank=True, null=True)),
                ('last_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_listings', to='stores.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'listings_storelisting',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['store', 'status'], name='listing_store_status')],
            },
        ),
        migrations.AddConstraint(
            model_name='storelisting',
            constraint=models.UniqueConstraint(fields=('store', 'external_variant_key', 'environment'), name='uq_listing_store_variant_env'),
        ),
        migrations.AddConstraint(
            model_name='marketplaceorder',
            constraint=models.UniqueConstraint(fields=('store', 'external_order_key', 'environment'), name='uq_order_store_key_env'),
        ),
    ]
