# Generated by Django 4.2.30 on 2026-07-14 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0022_store_lasoo_environment_and_more'),
        ('listings', '0003_storelisting_vendor_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_ticket_key', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('subject', models.CharField(blank=True, default='', max_length=500)),
                ('customer_name', models.CharField(blank=True, default='', max_length=255)),
                ('customer_email', models.CharField(blank=True, default='', max_length=255)),
                ('related_order_key', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('answered', 'Answered'), ('closed', 'Closed')], db_index=True, default='open', max_length=30)),
                ('unread_count', models.IntegerField(default=0)),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_customer_message_at', models.DateTimeField(blank=True, null=True)),
                ('environment', models.CharField(choices=[('staging', 'Staging'), ('production', 'Production')], default='staging', max_length=20)),
                ('raw_response_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='stores.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'listings_supportticket',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_message_key', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound (customer)'), ('outbound', 'Outbound (seller)'), ('system', 'System')], default='inbound', max_length=20)),
                ('body', models.TextField(blank=True, default='')),
                ('sender_name', models.CharField(blank=True, default='', max_length=255)),
                ('sender_type', models.CharField(blank=True, default='', max_length=50)),
                ('delivered_to_marketplace', models.BooleanField(default=False)),
                ('marketplace_request_json', models.JSONField(blank=True, null=True)),
                ('marketplace_response_json', models.JSONField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='listings.supportticket')),
            ],
            options={
                'db_table': 'listings_ticketmessage',
                'ordering': ['sent_at', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['store', 'status'], name='ticket_store_status'),
        ),
        migrations.AddConstraint(
            model_name='supportticket',
            constraint=models.UniqueConstraint(fields=('store', 'external_ticket_key', 'environment'), name='uq_ticket_store_key_env'),
        ),
    ]
