# Generated by Django 6.0.3 on 2026-03-04 20:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('multiplier', models.FloatField(default=1.0)),
                ('optional_fee', models.FloatField(default=0.0)),
                ('rounding_option', models.CharField(choices=[('none', 'No Rounding'), ('nearest_99', 'Nearest .99'), ('nearest_int', 'Nearest Integer'), ('ceil', 'Ceiling'), ('floor', 'Floor')], default='none', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StockRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_type', models.CharField(choices=[('multiplier', 'Multiplier'), ('fixed', 'Fixed Quantity'), ('cap', 'Cap (Maximum)'), ('floor', 'Floor (Minimum)')], default='multiplier', max_length=20)),
                ('value', models.IntegerField(default=1)),
                ('zero_if_low', models.BooleanField(default=True, help_text="Treat '1 left' as 0")),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('platform', models.CharField(help_text='e.g., Reverb, Kogan, MyDeal, Walmart, Sears, Etsy', max_length=100)),
                ('region', models.CharField(choices=[('USA', 'USA'), ('AU', 'Australia')], max_length=10)),
                ('api_token', models.TextField(help_text='Will be encrypted in production')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
