# Generated by Django 4.2.29 on 2026-03-06 18:04

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='api_token',
            field=core.fields.EncryptedTextField(help_text='Encrypted at rest; set ENCRYPTION_KEY in production'),
        ),
    ]
