# Generated by Django 4.2.29 on 2026-03-13 01:36

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0001_initial'),
        ('marketplace', '0002_initial'),
        ('stores', '0003_use_encrypted_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorePriceRange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_value', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('to_value', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'stores_storepricerange',
                'ordering': ['from_value'],
            },
        ),
        migrations.AddField(
            model_name='store',
            name='marketplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores_legacy', to='marketplace.marketplace'),
        ),
        migrations.AddField(
            model_name='store',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='StoreVendorPriceSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purchase_tax_percentage', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=5, null=True)),
                ('marketplace_fees_percentage', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_price_settings', to='stores.store')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_legacy_price_settings', to='vendor.vendor')),
            ],
            options={
                'verbose_name_plural': 'Store vendor price settings',
                'db_table': 'stores_storevendorpricesettings',
                'unique_together': {('store', 'vendor')},
            },
        ),
        migrations.CreateModel(
            name='StoreVendorInventorySettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_inventory_settings', to='stores.store')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_legacy_inventory_settings', to='vendor.vendor')),
            ],
            options={
                'verbose_name_plural': 'Store vendor inventory settings',
                'db_table': 'stores_storevendorinventorysettings',
                'unique_together': {('store', 'vendor')},
            },
        ),
        migrations.CreateModel(
            name='StoreInventoryRangeMultiplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_value', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('to_value', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('multiplier', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='range_multipliers', to='stores.storevendorinventorysettings')),
            ],
            options={
                'verbose_name_plural': 'Store inventory range multipliers',
                'db_table': 'stores_storeinventoryrangemultiplier',
            },
        ),
        migrations.CreateModel(
            name='StorePriceRangeMargin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('margin_percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('minimum_margin_cents', models.IntegerField(blank=True, default=0, null=True)),
                ('dont_pay_discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='margins', to='stores.storepricerange')),
                ('price_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='range_margins', to='stores.storevendorpricesettings')),
            ],
            options={
                'verbose_name_plural': 'Store price range margins',
                'db_table': 'stores_storepricerangemargin',
                'unique_together': {('price_settings', 'price_range')},
            },
        ),
    ]
