# Generated by Django 4.2.29 on 2026-03-13 02:50

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0001_initial'),
        ('stores', '0004_add_vendor_price_inventory_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockrule',
            name='store',
        ),
        migrations.AddField(
            model_name='storevendorinventorysettings',
            name='default_multiplier',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('1'), max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='storevendorinventorysettings',
            name='default_value',
            field=models.IntegerField(default=1, help_text='For fixed/cap/floor rules'),
        ),
        migrations.AddField(
            model_name='storevendorinventorysettings',
            name='rule_type',
            field=models.CharField(choices=[('multiplier', 'Multiplier'), ('fixed', 'Fixed Quantity'), ('cap', 'Cap (Maximum)'), ('floor', 'Floor (Minimum)')], default='multiplier', max_length=20),
        ),
        migrations.AddField(
            model_name='storevendorinventorysettings',
            name='zero_if_low',
            field=models.BooleanField(default=True, help_text="Treat '1 left' as 0"),
        ),
        migrations.AddField(
            model_name='storevendorpricesettings',
            name='multiplier',
            field=models.FloatField(default=1.0, help_text='Fallback when no tier matches'),
        ),
        migrations.AddField(
            model_name='storevendorpricesettings',
            name='optional_fee',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='storevendorpricesettings',
            name='rounding_option',
            field=models.CharField(choices=[('none', 'No Rounding'), ('nearest_99', 'Nearest .99'), ('nearest_int', 'Nearest Integer'), ('ceil', 'Ceiling'), ('floor', 'Floor')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='store',
            name='platform',
            field=models.CharField(blank=True, help_text='Derived from marketplace.name; kept for backward compat', max_length=100),
        ),
        migrations.AlterField(
            model_name='storevendorinventorysettings',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_vendor_inventory_settings', to='vendor.vendor'),
        ),
        migrations.AlterField(
            model_name='storevendorpricesettings',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_vendor_price_settings', to='vendor.vendor'),
        ),
        migrations.DeleteModel(
            name='PricingRule',
        ),
        migrations.DeleteModel(
            name='StockRule',
        ),
    ]
