# Generated by Django 4.2.29 on 2026-03-14 08:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_inventory_range_type_and_fixed_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeinventoryrangemultiplier',
            name='fixed_value',
            field=models.IntegerField(blank=True, help_text='Store stock when range_type=fixed', null=True),
        ),
        migrations.AlterField(
            model_name='storeinventoryrangemultiplier',
            name='multiplier',
            field=models.DecimalField(decimal_places=4, default=Decimal('1'), help_text='Used when range_type=multiplier', max_digits=8),
        ),
    ]
