# Generated by Django 4.2.29 on 2026-03-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_alter_storeinventoryrangemultiplier_fixed_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether store is active for syncing'),
        ),
    ]
