# Generated by Django 4.2.29 on 2026-03-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_add_store_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='connection_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('connected', 'Connected'), ('error', 'Error')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='store',
            name='last_validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
