# Generated by Django 4.2.29 on 2026-03-25 15:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_add_connection_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storepricerangemargin',
            name='margin_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Multiplier on cost after purchase tax (e.g. 2.2 → list price = cost × 2.2).', max_digits=6),
        ),
    ]
