# Generated by Django 4.2.29 on 2026-04-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0013_storepricerangemargin_margin_type_direct'),
    ]

    operations = [
        migrations.AddField(
            model_name='storevendorpricesettings',
            name='continuous_update',
            field=models.BooleanField(default=False, help_text='If True, only push listing updates to the marketplace when vendor price/stock changed since last scrape.'),
        ),
        migrations.AddConstraint(
            model_name='store',
            constraint=models.UniqueConstraint(fields=('user', 'name', 'marketplace'), name='uq_store_user_name_marketplace'),
        ),
    ]
