# Generated by Django 4.2.29 on 2026-04-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0014_product_scrape_and_store_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='catalog_pending_reset_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When reached, active catalog listings sync_status reset to pending (24h after marketplace sync).', null=True),
        ),
    ]
