# Generated by Django 4.2.29 on 2026-04-16 14:23

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0015_catalog_activity_and_pending_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='kogan_first_price_column',
            field=models.CharField(default='kogan_first_price', max_length=64),
        ),
        migrations.AddField(
            model_name='store',
            name='kogan_price_column',
            field=models.CharField(default='PRICE', max_length=64),
        ),
        migrations.AddField(
            model_name='store',
            name='kogan_rrp_column',
            field=models.CharField(default='rrp', max_length=64),
        ),
        migrations.AddField(
            model_name='store',
            name='kogan_service_account_json',
            field=core.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='kogan_sheet_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='kogan_sku_column',
            field=models.CharField(default='PRODUCT_SKU', max_length=64),
        ),
        migrations.AddField(
            model_name='store',
            name='kogan_stock_column',
            field=models.CharField(default='STOCK', max_length=64),
        ),
        migrations.AddField(
            model_name='store',
            name='kogan_tab_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
