# Generated by Django 4.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0016_store_kogan_first_price_column_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='catalog_zero_pending_at',
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text=(
                    'When server-scrapable listings first had none in Pending; 24h after this, '
                    'scraped/synced non-ingest-only rows return to Pending. Cleared if Pending reappears.'
                ),
                null=True,
            ),
        ),
    ]
