# Generated by Django 4.2.29 on 2026-05-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0018_store_mydeal_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='mydeal_profile',
            field=models.CharField(blank=True, choices=[('TFS', 'TFS'), ('P&P', 'P&P')], help_text='Mydeal template family: TFS or P&P.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='storevendorpricesettings',
            name='mydeal_rrp_margin_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Mydeal only: RRP(IncGST) = Price(IncGST) / (this % / 100).', max_digits=6, null=True),
        ),
    ]
