# Generated by Django 4.2.29 on 2026-07-13 12:33

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0021_storevendorpricesettings_kogan_price_margin'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='lasoo_environment',
            field=models.CharField(blank=True, choices=[('staging', 'Staging'), ('production', 'Production')], default='staging', help_text='Which Lasoo environment listing pushes / order pulls use by default.', max_length=20),
        ),
        migrations.AddField(
            model_name='store',
            name='lasoo_production_auth_key',
            field=core.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='lasoo_production_base_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='store',
            name='lasoo_staging_auth_key',
            field=core.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='lasoo_staging_base_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='store',
            name='management_mode',
            field=models.CharField(choices=[('inventory_only', 'Inventory only'), ('full_store', 'Managed store')], db_index=True, default='inventory_only', help_text='full_store = we manage listings, orders and shipping on the marketplace; inventory_only = we only sync price/stock for listings created elsewhere.', max_length=20),
        ),
        migrations.AlterField(
            model_name='storevendorpricesettings',
            name='mydeal_rrp_margin_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Mydeal, Sears, Kogan: RRP discount % off RRP. RRP = posted price / ((100 - this) / 100).', max_digits=6, null=True),
        ),
    ]
