# Generated by Django 4.2.29 on 2026-08-12 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0025_store_mydeal_api_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='credential_fingerprint',
            field=models.CharField(blank=True, db_index=True, default='', help_text='SHA-256 of marketplace credentials used to reclaim an orphaned store on reconnect.', max_length=64),
        ),
        migrations.AddField(
            model_name='store',
            name='orphaned_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When the owning user was deleted; store is retained until purge after STORE_ORPHAN_RETENTION_DAYS.', null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Null while orphaned after the owning user was deleted (retention window).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores', to=settings.AUTH_USER_MODEL),
        ),
    ]
