# Generated by Django 4.2.29 on 2026-03-13 01:14

import core.fields
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryRangeMultiplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('multiplier', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Inventory range multipliers',
                'db_table': 'marketplace_inventoryrangemultiplier',
            },
        ),
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'marketplace_marketplace',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PriceRange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_value', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('to_value', models.DecimalField(decimal_places=4, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'marketplace_pricerange',
                'ordering': ['from_value'],
            },
        ),
        migrations.CreateModel(
            name='PriceRangeMargin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('margin_percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('minimum_margin_cents', models.IntegerField(blank=True, default=0, null=True)),
                ('dont_pay_discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Price range margins',
                'db_table': 'marketplace_pricerangemargin',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('api_key_enc', core.fields.EncryptedTextField(blank=True, null=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('scraping_enabled', models.BooleanField(db_index=True, default=True)),
                ('scraping_interval_hours', models.PositiveIntegerField(blank=True, default=24, null=True)),
                ('last_scrape_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('price_update_enabled', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('method_type', models.CharField(choices=[('api', 'API'), ('oauth', 'OAuth'), ('manual', 'Manual')], default='api', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'marketplace_store',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreInventorySettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Store inventory settings',
                'db_table': 'marketplace_storeinventorysettings',
            },
        ),
        migrations.CreateModel(
            name='StoreTemplateUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('marketplace_code', models.CharField(db_index=True, max_length=50)),
                ('template_type', models.CharField(choices=[('product', 'Product'), ('inventory', 'Inventory'), ('custom', 'Custom')], max_length=20)),
                ('original_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_uploads', to='marketplace.store')),
            ],
            options={
                'db_table': 'marketplace_storetemplateupload',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='StorePriceSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purchase_tax_percentage', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=5, null=True)),
                ('marketplace_fees_percentage', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_settings', to='marketplace.store')),
            ],
            options={
                'verbose_name_plural': 'Store price settings',
                'db_table': 'marketplace_storepricesettings',
            },
        ),
    ]
