# Generated by Django 4.2.29 on 2026-03-13 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storepricesettings',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_price_settings', to='vendor.vendor'),
        ),
        migrations.AddField(
            model_name='storeinventorysettings',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_settings', to='marketplace.store'),
        ),
        migrations.AddField(
            model_name='storeinventorysettings',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_inventory_settings', to='vendor.vendor'),
        ),
        migrations.AddField(
            model_name='store',
            name='marketplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='marketplace.marketplace'),
        ),
        migrations.AddField(
            model_name='store',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_stores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pricerangemargin',
            name='price_range',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='margins', to='marketplace.pricerange'),
        ),
        migrations.AddField(
            model_name='pricerangemargin',
            name='price_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='range_margins', to='marketplace.storepricesettings'),
        ),
        migrations.AddField(
            model_name='inventoryrangemultiplier',
            name='inventory_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='range_multipliers', to='marketplace.storeinventorysettings'),
        ),
        migrations.AddField(
            model_name='inventoryrangemultiplier',
            name='price_range',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_multipliers', to='marketplace.pricerange'),
        ),
        migrations.AlterUniqueTogether(
            name='storepricesettings',
            unique_together={('store', 'vendor')},
        ),
        migrations.AlterUniqueTogether(
            name='storeinventorysettings',
            unique_together={('store', 'vendor')},
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['user', 'is_active'], name='mkt_store_user_active'),
        ),
        migrations.AlterUniqueTogether(
            name='pricerangemargin',
            unique_together={('price_settings', 'price_range')},
        ),
        migrations.AlterUniqueTogether(
            name='inventoryrangemultiplier',
            unique_together={('inventory_settings', 'price_range')},
        ),
    ]
