# Generated by Django 4.2.29 on 2026-03-13 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_switch_product_store_to_stores'),  # Product.store must point to stores.Store first
        ('marketplace', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pricerangemargin',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='pricerangemargin',
            name='price_range',
        ),
        migrations.RemoveField(
            model_name='pricerangemargin',
            name='price_settings',
        ),
        migrations.RemoveField(
            model_name='store',
            name='marketplace',
        ),
        migrations.RemoveField(
            model_name='store',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='storeinventorysettings',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='storeinventorysettings',
            name='store',
        ),
        migrations.RemoveField(
            model_name='storeinventorysettings',
            name='vendor',
        ),
        migrations.AlterUniqueTogether(
            name='storepricesettings',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='storepricesettings',
            name='store',
        ),
        migrations.RemoveField(
            model_name='storepricesettings',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='storetemplateupload',
            name='store',
        ),
        migrations.DeleteModel(
            name='InventoryRangeMultiplier',
        ),
        migrations.DeleteModel(
            name='PriceRange',
        ),
        migrations.DeleteModel(
            name='PriceRangeMargin',
        ),
    ]
