# Generated by Django 4.2.29 on 2026-03-13 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_switch_product_store_to_stores'),
        ('marketplace', '0003_remove_duplicate_store_models'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Store',
        ),
        migrations.DeleteModel(
            name='StoreInventorySettings',
        ),
        migrations.DeleteModel(
            name='StorePriceSettings',
        ),
        migrations.DeleteModel(
            name='StoreTemplateUpload',
        ),
    ]
