from django.urls import path

from .views import (
    StoreListingBulkUploadView,
    StoreListingDetailView,
    StoreListingListCreateView,
    StoreListingPhotoUploadView,
    StoreListingPublishView,
    StoreListingTemplateView,
    StoreListingUploadHistoryView,
    StoreOrderCancelReasonsView,
    StoreOrderCancelView,
    StoreOrderShippingCompleteView,
    StoreOrderShippingView,
    StoreOrdersExportView,
    StoreOrdersView,
    StoreOrderTestView,
    StoreReverbCategoriesView,
    StoreReverbConditionsView,
    StoreTicketReplyView,
    StoreTicketsExportView,
    StoreTicketsView,
    StoreTicketTestView,
)

urlpatterns = [
    path('stores/<uuid:store_pk>/listings/', StoreListingListCreateView.as_view(), name='store-listings'),
    path('stores/<uuid:store_pk>/listings/photos/', StoreListingPhotoUploadView.as_view(), name='store-listings-photos'),
    path('stores/<uuid:store_pk>/listings/reverb/categories/', StoreReverbCategoriesView.as_view(), name='store-reverb-categories'),
    path('stores/<uuid:store_pk>/listings/reverb/conditions/', StoreReverbConditionsView.as_view(), name='store-reverb-conditions'),
    path('stores/<uuid:store_pk>/listings/template/', StoreListingTemplateView.as_view(), name='store-listings-template'),
    path('stores/<uuid:store_pk>/listings/bulk-upload/', StoreListingBulkUploadView.as_view(), name='store-listings-bulk-upload'),
    path('stores/<uuid:store_pk>/listings/uploads/', StoreListingUploadHistoryView.as_view(), name='store-listings-uploads'),
    path('stores/<uuid:store_pk>/listings/publish/', StoreListingPublishView.as_view(), name='store-listings-publish'),
    path('stores/<uuid:store_pk>/listings/<uuid:pk>/', StoreListingDetailView.as_view(), name='store-listing-detail'),
    path('stores/<uuid:store_pk>/orders/', StoreOrdersView.as_view(), name='store-orders'),
    path('stores/<uuid:store_pk>/orders/export/', StoreOrdersExportView.as_view(), name='store-orders-export'),
    path('stores/<uuid:store_pk>/orders/test/', StoreOrderTestView.as_view(), name='store-orders-test'),
    path('stores/<uuid:store_pk>/orders/cancel-reasons/', StoreOrderCancelReasonsView.as_view(), name='store-order-cancel-reasons'),
    path('stores/<uuid:store_pk>/orders/<uuid:pk>/shipping/', StoreOrderShippingView.as_view(), name='store-order-shipping'),
    path('stores/<uuid:store_pk>/orders/<uuid:pk>/shipping/complete/', StoreOrderShippingCompleteView.as_view(), name='store-order-shipping-complete'),
    path('stores/<uuid:store_pk>/orders/<uuid:pk>/cancel/', StoreOrderCancelView.as_view(), name='store-order-cancel'),
    path('stores/<uuid:store_pk>/tickets/', StoreTicketsView.as_view(), name='store-tickets'),
    path('stores/<uuid:store_pk>/tickets/export/', StoreTicketsExportView.as_view(), name='store-tickets-export'),
    path('stores/<uuid:store_pk>/tickets/test/', StoreTicketTestView.as_view(), name='store-tickets-test'),
    path('stores/<uuid:store_pk>/tickets/<uuid:pk>/reply/', StoreTicketReplyView.as_view(), name='store-ticket-reply'),
]
