# Generated by Django 4.2

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStoreMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('orders_count', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('out_of_stock_count', models.IntegerField(default=0)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='stores.store')),
            ],
            options={
                'ordering': ['-date'],
                'verbose_name_plural': 'Daily store metrics',
            },
        ),
        migrations.AddConstraint(
            model_name='dailystoremetrics',
            constraint=models.UniqueConstraint(fields=('store', 'date'), name='analytics_dailystoremetrics_store_date_unique'),
        ),
    ]
