# Generated by Django 4.2.29 on 2026-03-06 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_use_encrypted_token'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dailystoremetrics',
            name='analytics_dailystoremetrics_store_date_unique',
        ),
        migrations.AlterUniqueTogether(
            name='dailystoremetrics',
            unique_together={('store', 'date')},
        ),
    ]
