# Generated by Django 6.0.3 on 2026-03-04 20:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('vendor_url', models.URLField(max_length=1000)),
                ('vendor_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vendor_stock', models.IntegerField(blank=True, null=True)),
                ('store_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('store_stock', models.IntegerField(blank=True, null=True)),
                ('sync_status', models.CharField(default='pending', max_length=50)),
                ('last_sync_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
