# Generated by Django 4.2.29 on 2026-03-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmapping',
            name='failed_sync_count',
            field=models.IntegerField(default=0, help_text='Consecutive failures; needs_attention when >= 3'),
        ),
    ]
