# Generated by Django 4.2.29 on 2026-03-13 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0001_initial'),
        ('catalog', '0003_add_failed_sync_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmapping',
            options={'ordering': ['sku']},
        ),
        migrations.AddField(
            model_name='productmapping',
            name='marketplace_child_sku',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='marketplace_parent_sku',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='vendor.vendor'),
        ),
        migrations.AlterField(
            model_name='productmapping',
            name='failed_sync_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productmapping',
            name='sku',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='productmapping',
            name='store_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='productmapping',
            name='sync_status',
            field=models.CharField(db_index=True, default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='productmapping',
            name='vendor_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterModelTable(
            name='productmapping',
            table='catalog_productmapping',
        ),
    ]
