# Generated by Django 4.2.29 on 2026-03-13 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_redundant_productmapping_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmapping',
            options={'ordering': ['product__vendor_sku']},
        ),
    ]
