# Generated by Django 4.2.29 on 2026-03-17 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_upload_user_store'),
        ('vendor', '0002_add_is_valid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0008_alter_storeinventoryrangemultiplier_fixed_value_and_more'),
        ('catalog', '0009_alter_productmapping_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('processed_rows', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('validated', 'Validated'), ('processing', 'Processing'), ('synced', 'Synced'), ('partial', 'Partial'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('error_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_uploads', to='stores.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'catalog_catalogupload',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='productmapping',
            name='is_active',
            field=models.BooleanField(default=True, help_text='False = soft-deleted; will end listing on Reverb during Update'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='marketplace_id',
            field=models.CharField(blank=True, db_index=True, help_text='Reverb listing ID for API updates', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ReverbUpdateLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('pushed_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('pushed_stock', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reverb_update_logs', to='catalog.productmapping')),
            ],
            options={
                'db_table': 'catalog_reverbupdatelog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CatalogUploadRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.PositiveIntegerField()),
                ('vendor_name_raw', models.CharField(max_length=255)),
                ('vendor_id_raw', models.CharField(blank=True, default='', max_length=255)),
                ('is_variation_raw', models.CharField(blank=True, default='', max_length=50)),
                ('variation_id_raw', models.CharField(blank=True, default='', max_length=255)),
                ('marketplace_name_raw', models.CharField(blank=True, default='', max_length=255)),
                ('store_name_raw', models.CharField(max_length=255)),
                ('marketplace_parent_sku_raw', models.CharField(blank=True, default='', max_length=255)),
                ('marketplace_child_sku_raw', models.CharField(blank=True, default='', max_length=255)),
                ('marketplace_id_raw', models.CharField(blank=True, default='', max_length=255)),
                ('vendor_sku_raw', models.CharField(blank=True, default='', max_length=255)),
                ('vendor_url_raw', models.CharField(blank=True, default='', max_length=1000)),
                ('action_raw', models.CharField(default='Add', max_length=20)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('added', 'Added'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('skipped', 'Skipped'), ('error', 'Error')], db_index=True, default='pending', max_length=20)),
                ('sync_error', models.TextField(blank=True, null=True)),
                ('catalog_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='catalog.catalogupload')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_upload_rows', to='products.product')),
                ('product_mapping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_upload_rows', to='catalog.productmapping')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalog_upload_rows', to='stores.store')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_upload_rows', to='vendor.vendor')),
            ],
            options={
                'db_table': 'catalog_cataloguploadrow',
                'ordering': ['catalog_upload', 'row_number'],
            },
        ),
        migrations.CreateModel(
            name='CatalogSyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('add', 'Add'), ('update', 'Update'), ('delete', 'Delete')], max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('skipped', 'Skipped'), ('error', 'Error')], max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('catalog_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='catalog.catalogupload')),
                ('catalog_upload_row', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sync_log', to='catalog.cataloguploadrow')),
            ],
            options={
                'db_table': 'catalog_catalogsynclog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='cataloguploadrow',
            constraint=models.UniqueConstraint(fields=('catalog_upload', 'row_number'), name='uq_cataloguploadrow_upload_row'),
        ),
    ]
