# Generated by Django 4.2.29 on 2026-04-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_catalogupload_productmapping_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmapping',
            name='last_scrape_time',
            field=models.DateTimeField(blank=True, help_text='Last successful scrape that applied vendor price/stock locally.', null=True),
        ),
    ]
