# Generated by Django 4.2.29 on 2026-04-05 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0015_catalog_activity_and_pending_reset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0011_product_scrape_and_store_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(db_index=True, max_length=64)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_activity_logs', to='stores.store')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'catalog_catalogactivitylog',
                'ordering': ['-created_at'],
            },
        ),
    ]
