# Generated by Django 4.2.29 on 2026-04-22 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0017_store_catalog_zero_pending_at'),
        ('catalog', '0018_productmapping_scrape_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreCatalogCeleryScrapeState',
            fields=[
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='catalog_celery_scrape_state', serialize=False, to='stores.store')),
                ('scope', models.CharField(choices=[('store', 'Store-wide'), ('upload', 'Upload-scoped')], default='store', max_length=16)),
                ('root_task_id', models.CharField(blank=True, help_text='Celery task id of the enqueued top-level task (for debugging).', max_length=255)),
                ('enqueued_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='celery_scrape_states', to='catalog.catalogupload')),
            ],
            options={
                'db_table': 'catalog_storeceleryscrapestate',
            },
        ),
    ]
