# Generated by Django 4.2.29 on 2026-04-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_store_catalog_celery_scrape_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogupload',
            name='source_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='catalog_uploads/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='catalogupload',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ingesting', 'Ingesting'), ('validated', 'Validated'), ('processing', 'Processing'), ('synced', 'Synced'), ('partial', 'Partial'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='catalogupload',
            index=models.Index(fields=['store', '-created_at'], name='catalog_upl_store_created'),
        ),
    ]
