# Generated by Django 4.2.29 on 2026-08-12 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0027_walmart_fulfillment_lag_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogupload',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_uploads', to=settings.AUTH_USER_MODEL),
        ),
    ]
