# Generated by Django 4.2.29 on 2026-03-13 01:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor_sku', models.CharField(db_index=True, max_length=255)),
                ('variation_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('marketplace_child_sku', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('marketplace_parent_sku', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('marketplace_price_external_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('marketplace_final_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('marketplace_final_inventory', models.PositiveIntegerField(blank=True, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='marketplace.store')),
            ],
            options={
                'db_table': 'products_product',
                'ordering': ['vendor_sku'],
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_name', models.CharField(max_length=255)),
                ('stored_key', models.CharField(blank=True, db_index=True, max_length=500, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('processed_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20)),
                ('progress_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'products_upload',
                'ordering': ['-completed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Scrape',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scrape_time', models.DateTimeField(db_index=True)),
                ('price_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('stock', models.PositiveIntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('calculated_shipping_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('error_details', models.TextField(blank=True, null=True)),
                ('final_inventory', models.PositiveIntegerField(blank=True, null=True)),
                ('final_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('needs_rescrape', models.BooleanField(db_index=True, default=False)),
                ('raw_ended_listings', models.JSONField(blank=True, null=True)),
                ('raw_handling_time', models.JSONField(blank=True, null=True)),
                ('raw_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('raw_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('raw_seller_away', models.JSONField(blank=True, null=True)),
                ('raw_shipping', models.JSONField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrapes', to='products.product')),
            ],
            options={
                'db_table': 'products_scrape',
                'ordering': ['-scrape_time'],
                'get_latest_by': 'scrape_time',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.upload'),
        ),
    ]
