# Generated by Django 4.2.29 on 2026-03-13 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='vendor.vendor'),
        ),
        migrations.AddIndex(
            model_name='scrape',
            index=models.Index(fields=['product', '-scrape_time'], name='scrape_prod_time'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['store', 'vendor'], name='prod_store_vendor'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['marketplace_child_sku'], name='prod_mkt_child_sku'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('store', 'vendor_sku')},
        ),
    ]
